---
title: "Analysis about TE predictions which do no map to Buchnera genome"
author: "Kamély Lumière"
date: "04/05/2023"
output: html_document
---


### I remove the 500 predictions from the initial db to have a database with prediction which do not map to Buchnera genome
### I used the awk cmd: awk 'BEGIN{while((getline<"ids_to_remove.txt")>0)l[">"$1]=1}/^>/{f=!l[$1]}f' aphid_TE_db_G1.fa > aphid_TE_db_G1_rm500.fa
### The file named aphid_TE_db_G1_rm500.fa contains only predictions which doesn't map to the Bucnera genome





```{r}

length_db_rm500<- read.table(file ="C:/Users/Anne-Flore/Desktop/klum/Buchnera/length_db_rm500.txt", header = TRUE); id_rm500 #ids of predictions which last in the final database

dfrm500<-data.frame(length_db_rm500 )
dfrm500
#to find the minimum and the maximum length
min(dfrm500[2]) #76
max(dfrm500[2]) #L38 336
dfrm500$Ids[dfrm500$Length==38336]

```




```{r}

#REX
a<-dfrm500$Length[substr(dfrm500$Ids[],1,3)=="REX"];a
min(a)
max(a)


#RDN
b<-dfrm500$Length[substr(dfrm500$Ids[],1,3)=="RDN"];b
min(b)
max(b)


```



```{r }

```
